Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022

.github/ISSUE_TEMPLATE/---bug-report.md, .github/ISSUE_TEMPLATE/---feature-request.md, .github/ISSUE_TEMPLATE/--design-fix.md, .github/ISSUE_TEMPLATE/--new-updated-design-content.md, .github/pull_request_template.md
=> Pull request&issue templates

code_of_conduct.md
I have made a curated list on behalf of the community on code-of-conduct which should be followed by all contributors for the success of this project
=> code-of-conduct

README.md
reformatted the link
- reformatted the changes made to the readme file
=> fix #contribution link in the readme file

LICENSE, README.md
🛠️ Added an MIT License 🛡
After going through the list of github authourized licenses, i found out that the MIT LICENSE is the best fit for this project. Have a look!
=> created a license for the project

CONTRIBUTING.md, style_guide.md
Closes #96
- Added explanation of the project structure to CONTRIBUTING.md
- Created a style_guide.md which contains style guide information from the figma board.
=> Added New Pull Request project structure and style guide to CONTRIBUTING.md

CONTRIBUTING.md
Closes #117 
I added more details to the contribution guidelines to explain properly what to do before submitting changes to avoid merge conflicts.
Let me know if there's more I can add to this commit
=> added more details about submitting changes

Design.md
@De-mi-de and I came up with the style guide and solved issue #101 
- The design style guide included Logo, Colors, Typography, Iconography, Form fields, Buttons and Alerts for desktop, tablet and mobile screens.
- The importance of the style guide is to ensure consistency throughout the design.
Co-authored-by: De-mi-de <olowosileanuoluwapo@gmail.com>
=> Design Style Guide

Design.md
@De-mi-de and I solved issue #102 
Using the style guide, user flow and design brief, @De-mi-de  and I designed a fully responsive landing page for the platform.
Co-authored-by: De-mi-de <olowosileanuoluwapo@gmail.com>
=> Landing Page Design

Design.md
=> Improved Landing Page UX Writing

Design.md
- I worked on the alignment and hierarchy of the landing page
- Improved the Create an account button placement within the margin and the navigation content was center aligned.
- Improved the arrow in the text button in was changed from a decimal to a whole number, because decimals are not advised in designs to ease the work of developers when implementing the design.
- Improved The arrow underneath the text from decimal to a whole, and made to have consistent height and width.
- Improved the user flow, there is meant to be a “wishlist icon” not “an add to cart icon” because this a P2P platform where there is no form of payment to be done on the app.
- Improved the contents in the footer were changed to be properly aligned with the margin.
- Improved the logo in the footer from “Martz” to …
=>  Improve Visual Hierachy and Alignment on the Landing Page

Design.md
Co-authored-by: nhorah <neboesomi@gmail.com>
Closes #103
=>  Design Authentication Screens (Create an Account)

Design.md
=> UX Writing for Authentication Screens

Design.md
Co-authored-by: De-mi-de <olowosileanuoluwapo@gmail.com>
Closes #106
=> Design User Dashboard: Home

Design.md
=> I Improved The UX Writing On The Authentication screens

Design.md
=> Design terms of service and the privacy policy page for the landing page

Design.md
=> I designed the Product description pop up for the User dashboard.

Design.md
I wrote a well drafted and well researched privacy policy statement in line with the project's goals and intended scope of operation. I concisely defined the concept of "cookies" to further aid the users' understanding.
Closes #128
=> Improve UX writing of Privacy Policy

Design.md
Co-authored-by: nhorah <neboesomi@gmail.com>
Closes #108
=> User Dashboard: View Uploaded Products Screen

Design.md
I designed a responsive product upload screen for both empty state and filled state for the product upload screen on the user dashboard
Closes #109
=> User dashboard ( Product upload page)

Design.md
I designed a responsive product upload screen for the help & support screen on the user dashboard
Closes #115
=> User Dashboard: Help & Support

Design.md
I designed the message screens that allow users to send a message to the seller of a product they want to purchase.
- I designed the message screens that allow users to send a message to the the admin in deserving circumstances. 
- I designed an empty state page to indicate to a user that they have not sent or received any messages.
- I designed a filled state page to show t the user all the messages they have sent and received so far.
- The designs were made with responsiveness in mind- there are desktop, tablet and mobile screen designs.
- To ensure conaiatency, I made use of the colors, typography and icons on the style guide.
Closes #110
=>  User Dashboard: Messages

Design.md
I drafted and formulated the legal policy statement of the brand in line with applicable legal standards.
Closes #193
=> Improve UX writing of Legal Policy Statement

Design.md
=> I designed the Search Result not Found Page for the User dashboard

Design.md
=> I designed the Search Result Screen on the User Dashboard

Design.md
- I designed the Wishlist pages for the responsive screens of the platform
- I designed the empty states of each screens across the platform responsively
- Closes  #111
=> Design a responsive wishlist page

Design.md
I designed the select and delete product pages for the responsive screens of the platform
- I designed the dropdown for the select/delete state.
- Closes #112
=> Design select and delete product on wishlist

Design.md
- I designed the notification popup screen of each of the screens responsively
- I designed the empty state of the screen across the platform responsively.
-  Closed #114
=> Design a notification popup screen

Design.md
- I designed the profile page of the user and this has to do with designing display name, display picture, account details, reset password,  delete account popup e.t.c. 
- This design was doe responsively across the platform  starting from the desktop, tablet and mobile screens .
- Closes #116
=> Design a user profile page

Design.md
I worked on issue #124 by improving the visual balance and consistency of all elements on the User Dashboard screens.
Closes #124
=> Added my contribution on UI design

Design.md
I worked on issue #126 by replacing the logos and also improving the balance and consistency of all elements on the User Dashboard screens (mobile view).
Closes #126
=> Added my contribution to UI Design

Design.md
I worked on issue #130  by improving the visual hierarchy and UX writing of some elements on the User Dashboard - Wishlist screens
Closes #130
=> Added my contributions to the UI Design

Design.md
Close #139 
I designed the side navigation for the mobile screens on the user dashboard to ease navigation for users.
=> Addition of Side Navigation for User Dashboard - Mobile Closes Issue #139

Design.md
Closes #185
I designed the side navigation for the desktop screens for the admin dashboard to ease navigation for the admins
=> Design of Side Navigation for Admin Dashboard - Desktop

Design.md
Close #186 
I designed the side navigation for the tablet screens for the admin dashboard to ease navigation for the admin
=> Design of Side Navigation for Admin Dashboard - Tablet

src/components/atoms/SecondaryButton.jsx, src/pages/CreateAccount.jsx, src/pages/Home.jsx, src/pages/Login.jsx
=> add inline tailwind styles for buttons behaviour on hover and click

Design.md
=> Design of Admin User groups - Desktop

Design.md
=> Design of Admin User groups - Tablet

Design.md
=> Design of Admin User groups - Mobile

Design.md
Co-authored-by: TechFlow247 <adewoleabdulazeez4@gmail.com>
Co-authored-by: teenuade <adelesiabidemi@gmail.com>
Co-authored-by: Mimi1510 <afolabimaryamoladoyin@gmail.com>
Co-authored-by: Henryola05 <jegedeolatide@gmail.com>
Closes #157
=> Admin user flow

Design.md
=> Admin dashboard - Mobile View

Design.md
=> Admin dashboard: Search Results - Mobile View

Design.md
=> Admin dashboard: Delete Products - Mobile View

Design.md
=> Admin dashboard: Make Product Unavailable - Mobile View
